public record GetMemberVocablistsQueryDto();
public record GetMemberVocablistsResultDto();
public record GetVocablistQueryDto();
public record GetVocablistResultDto();
public record GetVocabQueryDto();
public record GetVocabResultDto();
public record UpdateVocablistDto();
public record InsertVocablistDto();
public record DeleteVocablistDto();